python -u python/stitch_images.py \
    --inputDir "/media/soham/D/Programs/DESY/IR-setup/Data/2021-10-13/Lyon_dee/no-disk2disk-connector_side/lamp_off" \
    --inputPattern "2Sinserts_m15deg-chiller_0deg-dee_lampoff_XXX_YYY.asc" \
    --geomFile "data/geometry_carbonFoam.xlsx" \
    --moduleType "2S" \
    --ringOpt "odd" \
    --side "top" \
    --originX 0 \
    --isPrototype \
    --originY 232 \
    --motorRefX 23427 0 \
    --stepxtomm 1565.44/28506 \
    --stepytomm 626.78/499614 \
    --mmtopix 364/93 \
    --cadImage "data/Lyon_Dee_cad_no-disk-to-disk-connector_side.png" \
    --cadImageOrigin 595 33 \
    --mmtopixCad 780/1565.44 \
    --coolCircFiles "data/coolingCircuit_2Sinserts_Lyon-dee-prototype.yml" \
